version: '3.8'

services:
  mcp-server:
    build: .
    ports:
      - "8080:8080"  # Main MCP server port (not used in HTTP transport)
      - "8081:8081"  # Health check and MCP HTTP endpoint port
    environment:
      - ENVIRONMENT=production
      - TRANSPORT_MODE=http
      - MCP_SERVER_PORT=8080
      - HEALTH_PORT=8081
      - EXPRESS_API_BASE_URL=${EXPRESS_API_BASE_URL:-https://dowhistle.herokuapp.com/v3}
      - LOG_LEVEL=INFO
      - RATE_LIMIT_PER_MINUTE=120
      - MAX_RETRIES=5
      - RETRY_DELAY=2.0
      - API_KEY=${API_KEY:-}
      - CONNECTION_TIMEOUT=30
      - REQUEST_TIMEOUT=30
      - CORS_ORIGINS=*
      - CORS_METHODS=GET,POST,OPTIONS
      - CORS_HEADERS=Content-Type,Authorization,X-Requested-With
    
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # # Optional: Add resource limits for production
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M
    #       cpus: '0.5'
    #     reservations:
    #       memory: 256M
    #       cpus: '0.25'
    
    # # Optional: Add logging configuration
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"